name: Publish Website

on:
  push:
    branches:
      - main


jobs:
  web-deploy:
    name: 🚀 Deploy Website Every Commit
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get Latest Code
      uses: actions/checkout@v3
    
    - name: 📂 Sync Files
      uses: SamKirkland/web-deploy@v1
      with:
        target-server: federico-cadierno.com
        remote-user: l0050844
        private-ssh-key: ${{ secrets.SSH_KEY }}
        destination-path: /home/l0050844/federico-cadierno.com/wp-content/themes/ryancv